export const BASE_URL = 'https://pokeapi.co/api/v2';

export const POKEMONS_COLORS = {
  normal: '#A8A77A',
  fire: '#EE8130',
  water: '#6390F0',
  electric: '#F7D02C',
  grass: '#7AC74C',
  ice: '#96D9D6',
  fighting: '#C22E28',
  poison: '#A33EA1',
  ground: '#E2BF65',
  flying: '#A98FF3',
  psychic: '#F95587',
  bug: '#A6B91A',
  rock: '#B6A136',
  ghost: '#735797',
  dragon: '#6F35FC',
  dark: '#705746',
  steel: '#B7B7CE',
  fairy: '#D685AD',
};

export const POKEMON_TYPE_ICONS = {
  normal: '../../assets/icons/normal.png',
  fire: '../../assets/icons/fire.png',
  water: '../../assets/icons/water.png',
  electric: '../../assets/icons/electric.png',
  grass: '../../assets/icons/grass.png',
  ice: '../../assets/icons/ice.png',
  fighting: '../../assets/icons/fighting.png',
  poison: '../../assets/icons/poison.png',
  ground: '../../assets/icons/ground.png',
  flying: '../../assets/icons/flying.png',
  psychic: '../../assets/icons/psychic.png',
  bug: '../../assets/icons/bug.png',
  rock: '../../assets/icons/rock.png',
  ghost: '../../assets/icons/poison.png',
  dragon: '../../assets/icons/dragon.png',
  dark: '../../assets/icons/dark.png',
  steel: '../../assets/icons/steel.png',
  fairy: '../../assets/icons/fairy.png',
};
